### ISSUE TITLE
Support envsubst to generate .env files from the actual environment

### ISSUE THREAD

**Issue by sazzer** [andrewmclagan/react-env#28]
The `envsubst` tool is available in the container already, and can be leveraged to automatically generate the `.env` files from environment variables passed in to the Docker container at runtime. This in turn can make things really flexible for configuring the running app by simply changing the runtime environment without needing to change the files inside the container in any way.

**Comment by sazzer** [comment]
I have since realised that this form of expansion already happens using any environment variables of the form `REACT_APP_*`, so it's not strictly *needed* to do something like this.

However, this can allow for more complicated expansions, such as interpolating values from the Docker environment into a single value for the webapp.

I do have a PR I'll put up for this in case there is interest and leave it up to you :)

**Comment by andrewmclagan** [comment]
YEP! this now works see the updated docs for 3.x.x

**Comment by nick4fake** [comment]
@andrewmclagan Not sure where is it noted in the docs. Could you please share a link?
