### ISSUE TITLE
Question: passing arguments to command

### ISSUE THREAD

**Issue by donferi** [andrewmclagan/react-env#40]
Hi, I see in the docs that I can do something like `react-env <command with arguments>` however I can't figure out the right syntax for this.

For example, I can't get the following to work, it doesn't pass `--watch` to jest:
```
react-env jest --watch
```
or any other command where I need to pas a `--flag`. What am I doing wrong?

**Comment by andrewmclagan** [comment]
Sorry have never tried it with arguments: `react-env next dev`. Should write tests to cover that. Whats the output?

**Comment by andrewmclagan** [comment]
Why are you attempting to run jest with this lib?

**Comment by donferi** [comment]
Sorry it was just an example, but I can't pass any flags to my server, eg: `--port`.

**Comment by andrewmclagan** [comment]
This has changed in the latest 3.x.x version:

```bash
react-env --key APP_ENV -- <command>
```
