### ISSUE TITLE
NPM showing package version v3

### ISSUE THREAD

**Issue by kossy** [andrewmclagan/react-env#45]
Hi, I can't see any updates or release notes for version 3+ which has been released on https://www.npmjs.com/package/@beam-australia/react-env was wondering if this was intentional or if the @beam-australia/react-env package maps somewhere else now?

**Comment by andrewmclagan** [comment]
Sorry - I have just updated the repo with breaking changes. Please see.

**Comment by andrewmclagan** [comment]
The docs have been updated to reflect these changes.
