### ISSUE TITLE
Use with NextJS

### ISSUE THREAD

**Issue by joshboley** [andrewmclagan/react-env#51]
Hi there.  This is a great package.  I have one problem though.  I haven't been able to figure out how to include the `__ENV.js` file in the client.

What I've done is added it in the `<Head>` in `_document.ts`.

This one doesn't seem to work.  From what I've read, Next requires files in `public` to be present at build time 🙄 
```
....
<Head>
  <script type="text/javascript" src="public/__ENV.js></script>
</Head>
....
```

I tried this based on some other comments I saw with people having this problem with Next.  
```
....
<Head>
  <script type="text/javascript" dangerouslySetInnerHTML={{__html: fs.readFileSync(path.join(process.cwd(), 'public/__ENV.js')}}></script>
</Head>
....
```

This works fine locally, but does not work when deployed in a Docker container.  I've tried loads and loads of different approaches to getting the path to resolve correctly, but it always resolves to a directory for some task runner, which I assume Next is delegating to for rendering, so the file location is always wrong.

I just wanted to check and see if you had any run-ins with this sort of thing before I find a new path for handling env vars.

Thanks in advance!

**Comment by andrewmclagan** [comment]
Hi. It needs to read:

```jsx
<Head>
  <script type="text/javascript" src="__ENV.js></script>
</Head>
```

In the Next.js docs, and the [example in this repository ](https://github.com/andrewmclagan/react-env/tree/master/examples/next.js)it shows you don't need to preposition anything with `public/` as all files are assumed to be in this directory as it's the only one visible to the web.
