### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by RickEyre** [andrewmclagan/react-env#59]
Does this work by overwriting the `public/__ENV` file at runtime?

**Comment by HeadFox** [comment]
Yes exactly :)
You shouldn't commit your __ENV. It's automatically created when you run the react-env command

**Comment by andrewmclagan** [comment]
Yes, usually you would never commit this file to your repository as it is generated every-time the application runs.

**Comment by RickEyre** [comment]
Great thank you!
