### ISSUE TITLE
Can this be used to pass env vars to docker container for NGINX?

### ISSUE THREAD

**Issue by ssc327** [andrewmclagan/react-env#66]
I have a react app and I want to run it in an NGINX container and also inject some configuration at runtime via environment variables. From what I can tell this is not possible because a nodejs runtime is required. Is that correct? If not, please point me to an example how I can run on NGINX and pass in env vars.

**Comment by andrewmclagan** [comment]
Im guessing if you are running your app behind Nginx without a `node` binary present inside the docker container you must have a pure static build? Such as a static next.js build or create-react-app.

If this is the case you cannot use this library without installing the `node` binary inside your container. This library builds the environment at runtime via a node cli `react-env` so it simply wont work without node being present. 

There are 100% other solutions, you could roll your own bash script or write a pre-compiled binary in something like Golang. That way you would not need `node` as a dependancy. But honestly... just install node inside your container its very small.

**Comment by gfox1984** [comment]
Hey, if this helps anyone, I was able to run `react-env` in my NGINX container by installing node, as suggested by @andrewmclagan. Here's my setup:

### Dockerfile

```
FROM nginx:alpine

# Install react-env (so we can run react-env to generate __ENV.js)
RUN apk add --update npm
RUN npm install -g @beam-australia/react-env
...

# Copy entrypoint
COPY ./docker-entrypoint.sh ./docker-entrypoint.sh

# Set permissions
RUN chmod +x docker-entrypoint.sh

# Generate __ENV.js and start nginx
ENTRYPOINT ["./docker-entrypoint.sh"]
```
### docker-entrypoint.sh
```
#!/usr/bin/env sh

react-env --dest /usr/share/nginx/html
nginx -g "daemon off;"

exec "$@"
```
 ### Notes:
- my static app is copied at `/usr/share/nginx/html` (so I use `react-env --dest /usr/share/nginx/html`).
- I could not notice any significant size difference in my docker image with or without node

@andrewmclagan I would suggest adding an example to the repo with a static deployment of CRA + nginx. The solution was not that trivial to implement.
