### ISSUE TITLE
window.__ENV undefined 

### ISSUE THREAD

**Issue by jamesicon** [andrewmclagan/react-env#68]
Hi there,

I tried upgrading to latest package version and none of my envs were loading. I checked the source code and looks like it was changed from window._env to  window.__ENV but when I check the global object window.__ENV is undefined but window._env still has all the envs stored there.

I have since downgraded but would like to upgrade once the above issue is resolved.

**Comment by andrewmclagan** [comment]
Hey @jamesicon. It's hard to diagnose your issues without more information.

There were major breaking changes from `3.x.x` onwards, mainly around the parameters. Please read the documentation :-) otherwise if you think there is an issue let us know!
