### ISSUE TITLE
Broken Docker image on Docker Hub

### ISSUE THREAD

**Issue by sazzer** [andrewmclagan/react-env#73]
I'm not sure if you're aware or not, but there is a Docker image on Docker Hub - https://hub.docker.com/r/beamaustralia/react-env - that runs a static website using react-env. 

This was fantastic back when I first found it. However, it's now not been updated in 2 years and doesn't work with the current version of react-env. Which means that if you use the latest react-env in your project but try to use this docker image to deploy it then you'll likely waste hours trying to work out why things are broken.

I know it's not actually yourself that created this image, and I can't work out who did create it in order to message them, but it seemed worth mentioning if it can somehow stop other people having the same waste of time that I've just had!

Cheers

**Comment by andrewmclagan** [comment]
Hello! It was actually me who created this image. I should deprecate it, there are instructions on how to build your own docker image with the `react-env` binary. It is super easy. We simply dont want to maintain one!

**Comment by andrewmclagan** [comment]
Thank you for the heads up!
