### ISSUE TITLE
Feedback/Docker Usage

### ISSUE THREAD

**Issue by zanechua** [andrewmclagan/react-env#76]
Hey Andrew,

Thanks for this package. It's a nifty package!

I have some questions/feedback after seeing the readme. Could we get a simple setup process for projects? You have good documentation around the usage but setup is entirely missing? I have to kinda figure out which npm package it is tied to.

I know it's https://www.npmjs.com/package/@beam-australia/react-env and going to the github link via there redirects to this repo but would immensely help so that people will know especially since it's published under `beam-australia` and not your name.

```bash
yarn add @beam-australia/react-env
```

Could we also get the `README.md` published to the npm package for more visibility about the usage for people who come through there.

I came from the discussion from next.js about not embedding secrets into the docker container. Based on the current instructions in the README, isn't that what seems to be suggested? The only difference is that it's not directly in the compiled files.

With that being said, we're able to do this with your package by mounting the docker image with the following

```bash
docker run -p 8080:3000 -v $(pwd)/.env.staging:/app/.env.staging next-app
```

This way the secrets are truly generated at run time with your entrypoint script assuming:

```bash
APP_ENV=staging yarn react-env --env APP_ENV
```

Would you like me to open a PR with changes to the README?

**Comment by andrewmclagan** [comment]
Hello Zan. Thank you for reaching out, these are great suggestions. Would be very happy to see a PR around this.

The repo used to belong to `beam-australia` and it was transferred to me (I wrote it) to continue support. I forgot to also rename the npm organisation. It's difficult to rename this as a lot of people depend on it.

**Comment by zanechua** [comment]
That's fine. we don't have to rename the package. Just figured we should add that into the readme so people immediately know which package to use.

Oh. I mainly meant the section for "getting started" which you usually see around repos.

E.g.

## Getting Started
```bash
yarn add @beam-australia/react-env
```


I can do up a PR with some changes and see if you like them as long as you are willing to review it.

**Comment by andrewmclagan** [comment]
Brilliant :-) that looks perfect
