### ISSUE TITLE
window.__ENV not available

### ISSUE THREAD

**Issue by silentlight** [andrewmclagan/react-env#77]
I see that __ENV.js is generated in public folder and it includes correct data. The problem is that when I go to browser console I don't see window.__ENV. Do I have to import that file somewhere?

**Comment by andrewmclagan** [comment]
Yes, it is a javascript file. You need to include it in your page 

```html
<script crossorigin="anonymous" defer="defer" integrity="sha512-YOzkTPNBhsGBHTWNXcjLCxYM3ANDGkp2gejU1oLAxIG4g8VAZJlFYJX2Eo//GCdStAeiby9Y2FecMxmDQwj+Ow==" type="application/javascript" src="https://github.githubassets.com/assets/chunk-vendor-60ece44c.js"></script>"
```
