### ISSUE TITLE
Improvement ideas and caveats

### ISSUE THREAD

**Issue by andrasferenczi** [andrewmclagan/react-env#89]
I tried to assemble this together with a `NextJS` app and using `Docker`. I don't think I'll use this library, but I want to leave a couple comments on this since I've spent quite a lot of time understanding the whole process.

## `<script>`

[Here](https://github.com/andrewmclagan/react-env/blob/master/examples/next.js/pages/index.js#L25) it is advised to import the `__ENV.js` script in the head like this:

```Javascript
<script src="/__ENV.js" />
```

Which is not optimal at all IMO. Just imagine that the page loads and then it makes a request back to the server to download the environment variables so it can retrieve the route of the api backend (for example).

The idea is that it should be inlined into the script. So the `__ENV.js` should be read inside the `_document.jsx` (and cached) and then set as `HTML` content.

## It does not work with ASO

About [Automatic Static Optimization](https://nextjs.org/docs/basic-features/environment-variables), the following is said:

> Note: In order to keep server-only secrets safe, Next.js replaces process.env.* with the correct values at build time. 

Which means that in case you use `process.env.*` in your code that will be optimized out, it will still be done in build time. The file will be generated in a `static` directory and it will not matter what variable you pass into the environment when you call `next start`, it simply does not matter anymore.

The only reason the [example works](https://github.com/andrewmclagan/react-env/blob/4d193537ab30ff19a5c92ed59d19a11c995c443b/examples/next.js/pages/index.js#L14) is because`getInitialProps` is overridden.

With that said, I don't understand why it is claimed that this library supports static site generation. I am kinda lost on this one.

---

Anyway, thanks for the library. It is really awesome that you published this in open source.

**Comment by andrewmclagan** [comment]
Thanks for checking out the repo. 

1. The ENV script tag is placed before the NextJS bundles. Script tags are loaded in order. Your assumption is incorrect.

2. In no way does this package break static optimisation. The example is incorrect sorry! i need to update that.
