### ISSUE TITLE
feature request - load vars from single json file like env-cmd

### ISSUE THREAD

**Issue by acharlop** [andrewmclagan/react-env#96]
Hey thanks for such a simple and basically only solution for next runtime variables. I was wondering if you would be open to a PR to load in the vars from a single json file for all environments. I find it makes for easier managing of variables

**Comment by andrewmclagan** [comment]
Thanks! :-) 

No sorry `.env` files is a pretty settled standard. We have standards for a reason, I would not want to encourage fragmentation in the community. That being said, you could easily implement that behaviour in your app with this package.
